# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yang/c_study

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yang/c_study

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yang/c_study/CMakeFiles /home/yang/c_study//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yang/c_study/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sort_lib

# Build rule for target.
sort_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sort_lib
.PHONY : sort_lib

# fast build rule for target.
sort_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_lib.dir/build.make CMakeFiles/sort_lib.dir/build
.PHONY : sort_lib/fast

#=============================================================================
# Target rules for targets named sort_experment

# Build rule for target.
sort_experment: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sort_experment
.PHONY : sort_experment

# fast build rule for target.
sort_experment/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/build
.PHONY : sort_experment/fast

sort.o: sort.c.o
.PHONY : sort.o

# target to build an object file
sort.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_lib.dir/build.make CMakeFiles/sort_lib.dir/sort.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort.c.o
.PHONY : sort.c.o

sort.i: sort.c.i
.PHONY : sort.i

# target to preprocess a source file
sort.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_lib.dir/build.make CMakeFiles/sort_lib.dir/sort.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort.c.i
.PHONY : sort.c.i

sort.s: sort.c.s
.PHONY : sort.s

# target to generate assembly for a file
sort.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_lib.dir/build.make CMakeFiles/sort_lib.dir/sort.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort.c.s
.PHONY : sort.c.s

sort_experment.o: sort_experment.c.o
.PHONY : sort_experment.o

# target to build an object file
sort_experment.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort_experment.c.o
.PHONY : sort_experment.c.o

sort_experment.i: sort_experment.c.i
.PHONY : sort_experment.i

# target to preprocess a source file
sort_experment.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort_experment.c.i
.PHONY : sort_experment.c.i

sort_experment.s: sort_experment.c.s
.PHONY : sort_experment.s

# target to generate assembly for a file
sort_experment.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sort_experment.dir/build.make CMakeFiles/sort_experment.dir/sort_experment.c.s
.PHONY : sort_experment.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sort_experment"
	@echo "... sort_lib"
	@echo "... sort.o"
	@echo "... sort.i"
	@echo "... sort.s"
	@echo "... sort_experment.o"
	@echo "... sort_experment.i"
	@echo "... sort_experment.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

