all: getchar exchange temperature temperature_for_version

getchar: 
	gcc -o getchar getchar.c

exchange: 
	gcc -o exchange exchage.c

temperature:
	gcc -o temperature temperature.c

temperature_for_version:
	gcc -o temperature_for_version temperature_for_version.c
